apiVersion: v1
kind: Service
metadata:
  name: ngo-service
  namespace: solidarytech
  labels:
    app: ngo-service
spec:
  type: ClusterIP
  selector:
    app: ngo-service
  ports:
    - name: http
      port: 8081
      targetPort: http
